USE AirAtlantique;

CREATE LOGIN Maintenance WITH PASSWORD = 'mdpmaintenance';

CREATE LOGIN Billet WITH PASSWORD = 'mdpbillet';

CREATE LOGIN Vol WITH PASSWORD = 'mdpvol';


CREATE USER Maintenance FOR LOGIN Maintenance;

CREATE USER Billet FOR LOGIN  Billet;

CREATE USER Vol FOR LOGIN Vol;


GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.Incident TO Maintenance;
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.Maintenance TO Maintenance;
GRANT SELECT, UPDATE, DELETE ON dbo.Plane TO Maintenance;

GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.Billet TO Billet;
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.BilletGP TO Billet;
GRANT SELECT, UPDATE, DELETE ON dbo.Price TO Billet;
GRANT SELECT, INSERT ON dbo.Trip TO Billet;
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.Passenger TO Billet;
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.Luggage TO Billet;

GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.Flight TO Vol;
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.Trip TO Vol;
GRANT SELECT, UPDATE, DELETE ON dbo.Plane TO Vol;

SELECT * FROM INFORMATION_SCHEMA.TABLE_PRIVILEGES;