//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetBdd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenance_Salaried
    {
        public int id_Maintenance { get; set; }
        public int id_Salaried { get; set; }
        public bool Leader { get; set; }
    
        public virtual Maintenance Maintenance { get; set; }
        public virtual Salaried Salaried { get; set; }
    }
}
