//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetBdd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salaried
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Salaried()
        {
            this.BilletGP = new HashSet<BilletGP>();
            this.Incident = new HashSet<Incident>();
            this.Maintenance_Salaried = new HashSet<Maintenance_Salaried>();
            this.Flight = new HashSet<Flight>();
        }
    
        public int id { get; set; }
        public int id_Airport { get; set; }
        public int id_Speciality { get; set; }
        public string Name { get; set; }
        public string First_Name { get; set; }
        public int Registration_Number { get; set; }
        public bool Availability { get; set; }
        public System.DateTime Date_Birth { get; set; }
        public System.DateTime Date_Hiring { get; set; }
        public string Nationality { get; set; }
        public Nullable<bool> License { get; set; }
    
        public virtual Airport Airport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BilletGP> BilletGP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incident> Incident { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintenance_Salaried> Maintenance_Salaried { get; set; }
        public virtual Speciality Speciality { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flight> Flight { get; set; }
    }
}
