//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirAtlantiqueORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Type()
        {
            this.Plane = new HashSet<Plane>();
        }
    
        public short id { get; set; }
        public string Name { get; set; }
        public string Motor { get; set; }
        public Nullable<short> Nb_Eco_Places { get; set; }
        public Nullable<short> Nb_EcoPrem_Places { get; set; }
        public Nullable<short> Nb_Business_Places { get; set; }
        public Nullable<short> Nb_Premiere_Places { get; set; }
        public short Nb_Crew_Places { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plane> Plane { get; set; }
    }
}
